export const projects = [
  {
    title: 'Toysplanet',
    description: "ToyPlanet is a full-stack, one-stop shop web application for people who want to buy & sell used toys with other users.",
      image: '/images/toysplanet.png',
      tags: ['Mongo', 'GraphQL', 'React', 'Node'],
    source: 'https://github.com/Chrisolsen1993/Toysplanet',
    visit: 'https://obscure-journey-81724.herokuapp.com/',
    id: 0,
  },
  {
    title: 'HR Management System',
    description:"'HR Management' is tool created to make the job of a HR rep easier, helps the HR to manage all employees, Help Branch Manger to Look over there branch, Helps executive look over there company and for employee to find the benefits all in one place and request time off by just a click of the button.",
    image: '/images/HRManagementSystem.png',
    tags: ['Javascript', 'Handlebars', 'Express.js', 'MySQL'],
    source: 'https://github.com/alifaizan786-op/HR_Management_System',
    visit: 'https://hrmanagement0.herokuapp.com/login',
    id: 1,
  },
  {
    title: 'Squid Games',
    description: "After you win each game you will move on to the next round, lose a game and start over! Can you complete all the rounds of mini games?",
    image: '/images/squid-games.PNG',
    tags: ['HTML', 'CSS', 'Javascript'],
    source: 'https://github.com/matthewjflanagan/Squid-Games',
    visit: 'https://matthewjflanagan.github.io/Squid-Games/',
    id: 2,
  },
  {
    title: 'Tech Blog',
    description: "CMS-style blog site for the purpose of publishing articles, blog posts, thoughts and opinions!",
      image: '/images/techBlog.png',
      tags: ['Javascript', 'Handlebars', 'Express.js'],
    source: 'https://github.com/matthewjflanagan/Tech-Blog',
    visit: 'https://nameless-spire-37534.herokuapp.com/',
    id: 3,
  },
  {
    title: 'JOBS 4 MORE',
    description: "Search for your dream job by filter entering in your desired location, job type, and experience! JOBS 4 MORE will direct you to all the results matching your criteria where you can click on them to find out more information about each job. ",
    image: '/images/notetaker.png',
    tags: ['HTML', 'CSS', 'Javascript', 'Third-party API'],
    source: 'https://github.com/matthewjflanagan/JOBS-4-MORE',
    visit: 'https://matthewjflanagan.github.io/JOBS-4-MORE/',
    id: 4,
  },

];

export const TimeLineData = [
  { year: 'May 2018', text: 'Graduate University of South Carolina with Bachelors of Science in Economics and Minor in Environmental Sciences', },
  { year: 'July 2018', text: 'Join CaroTrans Internatinal as a Documentation Specialist in Charleston, SC', },
  { year: 'May 2019', text: '110k Charleston Branch profit for 2018 - 2019 fiscal year', },
  { year: 'August 2019', text: 'Reassigned to Atlanta Branch for Account Executive role', },
  { year: 'April 2020', text: 'Account Executive Rookie of the Year', },
  { year: 'May 2020', text: '180k Atlanta Branch profit for 2019 - 2020 fiscal year', },
  { year: 'May 2021', text: '225k Atlanta Branch profit for 2020 - 2021 fiscal year', },
  { year: 'February 2022', text: 'Georgia Tech Full Stack Web Development course completed', },
  { year: 'May 2022', text: '$1.15 million Atlanta Branch profit for 2021 - 2022 fiscal year', },
];