export const projects = [
  {
    title: 'Toysplanet',
    description: "ToyPlanet is a full-stack, one-stop shop web application for people who want to buy & sell used toys with other users.",
      image: '/images/toysplanet.png',
      tags: ['Mongo', 'GraphQL', 'React', 'Node'],
    source: 'https://github.com/Chrisolsen1993/Toysplanet',
    visit: 'https://obscure-journey-81724.herokuapp.com/',
    id: 0,
  },
  {
    title: 'HR Management System',
    description:"'HR Management' is tool created to make the job of a HR rep easier, helps the HR to manage all employees, Help Branch Manger to Look over there branch, Helps executive look over there company and for employee to find the benefits all in one place and request time off by just a click of the button.",
    image: '/images/HRManagementSystem.png',
    tags: ['Javascript', 'Handlebars', 'Express.js', 'MySQL'],
    source: 'https://github.com/alifaizan786-op/HR_Management_System',
    visit: 'https://hrmanagement0.herokuapp.com/login',
    id: 1,
  },
  {
    title: 'Tech Blog',
    description: "CMS-style blog site for the purpose of publishing articles, blog posts, thoughts and opinions!",
      image: '/images/techBlog.png',
      tags: ['Javascript', 'Handlebars', 'Express.js'],
    source: 'https://github.com/matthewjflanagan/Tech-Blog',
    visit: 'https://nameless-spire-37534.herokuapp.com/',
    id: 2,
  },
  {
    title: 'Code Quiz',
    description: "The Code Quiz is a total of 6 questions! Get the question correct and you receive 1 point, get the question incorrect and your time left is reduced by 10 seconds....will you be able to score a perfect 6 before time runs out!?",
    image: '/images/codequiz.png',
    tags: ['HTML', 'CSS', 'Javascript'],
    source: 'https://github.com/matthewjflanagan/Code-Quiz',
    visit: 'https://matthewjflanagan.github.io/Code-Quiz/',
    id: 3,
  },
  {
    title: 'Squid Games',
    description: "After you win each game you will move on to the next round, lose a game and start over! Can you complete all the rounds of mini games?",
    image: '/images/squid-games.PNG',
    tags: ['HTML', 'CSS', 'Javascript'],
    source: 'https://github.com/matthewjflanagan/Squid-Games',
    visit: 'https://matthewjflanagan.github.io/Squid-Games/',
    id: 4,
  },
  {
    title: 'Vito Flanagan',
    description: "A website dedicated to pictures of Vito on his adventures!",
    image: '/images/vito.PNG',
    tags: ['React', 'Next.js', 'Sanity.io'],
    source: 'https://photoalbum-two.vercel.app/',
    visit: 'https://matthewjflanagan.github.io/Squid-Games/',
    id: 4,
  },
];

export const TimeLineData = [
  { year: 2018, text: 'Join logistics company in Charleston, SC', },
  { year: 2019, text: 'Move to Atlanta, GA for Account Executive role', },
  { year: 2020, text: 'Account Executive Rookie of the Year', },
  { year: 2021, text: 'Started Full-Stack Web Development bootcamp at Georgia Tech', },
  { year: 2022, text: 'Reached $1 million in project in current company & graduated from Georgia Tech', },
];